version: '3.9'

networks:
  database:
    name: database
    driver: bridge
  gateway:
    name: database
    external: true

services:
  gateway:
    image: 'ghcr.io/undercurrent-technologies/gateway:latest'
    container_name: 'gateway'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - database
      - gateway
    env_file:
      - .env
    ports:
      - 8080:8080
